baseURL = 'https://othermythos.com/'
languageCode = 'en-us'
title = 'OtherMythos'
theme = ''

[taxonomies]
tag = 'tags'
category = 'categories'

[params]
authorName = 'Edward Herbert'
copyrightYear = '2025-2026'
